### ISSUE TITLE
Dynamically update schedule

### ISSUE THREAD

**Issue by noahcussatti** [wtg/Shuttle-Tracker-Web#103]
Update the schedule to reflect the current week's times
![shuttle](https://user-images.githubusercontent.com/31413744/152058578-e57df4f1-c7da-4d6c-b5e7-74f635b0319f.PNG)

**Comment by Isaac-the-Man** [comment]
I've made a feature request to the server team for a new endpoint to fetch the current schedule. Here's the [issue](https://github.com/wtg/Shuttle-Tracker-Server/issues/33) for reference.

**Comment by Isaac-the-Man** [comment]
See #115 for API reference.

**Comment by Isaac-the-Man** [comment]
API URL is on https://shuttletracker.app/schedule
