### ISSUE TITLE
Modals blocked by announcement banner

### ISSUE THREAD

**Issue by Isaac-the-Man** [wtg/Shuttle-Tracker-Web#104]
Announcement blocking top part of the welcome modal. This is also the case for the color blind modal.
Suggested fix: move the modal a little bit down.
![image](https://user-images.githubusercontent.com/29915393/152559372-5b3a8028-59fb-4b68-9035-d5e195b3c5c8.png)

**Comment by michaelni678** [comment]
Moving the modals to the center of the screen (like over the map) might look better than just moving it a little bit down. I think it'll no longer block the "Shuttle Tracker" header on most devices.

**Comment by Isaac-the-Man** [comment]
Good idea. Don't worry about blocking the header or any other elements though, as the modal is suppose to be the center of focus in the entire UI.
