### ISSUE TITLE
Add an option to simulate announcements in development mode

### ISSUE THREAD

**Issue by michaelni678** [wtg/Shuttle-Tracker-Web#106]
Add a switch to settings in dev mode to show the announcements bar even when there are no actual announcements.
![image](https://user-images.githubusercontent.com/82001942/152664820-1879b5d4-e30d-4c21-b078-c514ebdd8d51.png)

**Comment by Gerzer** [comment]
This is a good idea! It'll continue the legacy of our legendary Bus 69...
