### ISSUE TITLE
Documentation for Tracker.vue

### ISSUE THREAD

**Issue by Isaac-the-Man** [wtg/Shuttle-Tracker-Web#107]
Add comments to document javascript code of `src/components/Tracker.vue`, following [JSDoc3](https://jsdoc.app/) standards.

**Comment by ninheart** [comment]
Is this an issue that I can work on?

**Comment by Gerzer** [comment]
> Is this an issue that I can work on?

Yeah, go ahead! In general, you don't need to ask permission; you can just assign yourself to an issue and start working.

(Unless @Isaac-the-Man has some objection...)

**Comment by Isaac-the-Man** [comment]
@ninheart No need to ask for permission. Go ahead! This is a good opportunity to understand and get started with this project.
