### ISSUE TITLE
[Bug Fix] Texts not in the same line in mobile phone

### ISSUE THREAD

**Issue by KPLJ** [wtg/Shuttle-Tracker-Web#11]
<img width="383" alt="image" src="https://user-images.githubusercontent.com/44724621/135687671-6c9d22dc-32da-40b9-a33d-edf1f174f1d7.png">

"This map refreshed every 5 seconds" and "Download iOS app" are not in the same line in the explorer of mobile phone.
They are defined in Footer.vue

**Comment by huynchu** [comment]
https://github.com/wtg/Shuttle-Tracker-Web/issues/10
