### ISSUE TITLE
Advanced setting to change the server URL

### ISSUE THREAD

**Issue by Gerzer** [wtg/Shuttle-Tracker-Web#111]
I would like that there be a setting to change the server base URL, like there is in the latest beta of the iOS/iPadOS app. All of the API requests should be relative to this base URL. For example, if you change the base URL to `https://staging.shuttletracker.app`, then all API requests to, say, `https://shuttletracker.app/buses` should instead go to `https://staging.shuttletracker.app/buses`. Ideally, the presence or absence of a trailing slash shouldn't matter; setting the base URL to `https://example.com` should have exactly the same effect as setting it to `https://example.com/`.

Since this is an advanced setting the misconfiguration of which could break the entire client, the setting should be hidden behind, perhaps, an "Advanced Settings" drop-down section, or something similar.

I'll leave it up to you to decide whether this setting should be persisted in a browser cookie. Not persisting it has the benefit of letting the user reload the page to fix a misconfiguration. Of course, the default value should always be `https://shuttletracker.app`.

**Comment by Isaac-the-Man** [comment]
I'd like it to be stored in the browser cookie too. Also there should be a permanent warning to remind the user that they are using the non-default API. I'm thinking that it should look something like this.
![image](https://user-images.githubusercontent.com/29915393/153033304-8780ed82-bf4b-4d51-a58d-36ae9895cf37.png)

**Comment by Gerzer** [comment]
I like the idea of a permanent badge.
