### ISSUE TITLE
Welcome prompt needs updating

### ISSUE THREAD

**Issue by anugrahaawasthi** [wtg/Shuttle-Tracker-Web#116]
The welcome prompt still has "Our Android app is coming soon!".  This could use an update with the URL to our Play Store link.

**Comment by noahcussatti** [comment]
I thought it was redundant to add a URL on the welcome prompt since it's already located on the bottom of the page (with the iOS as well).
![Welcome prompt](https://user-images.githubusercontent.com/31413744/154150204-c11348c4-a251-4cdb-9309-0328b322caad.PNG)

**Comment by anugrahaawasthi** [comment]
That also works! I guess the prompt only needs some small text fixes to reflect some recent changes (such as the iOS app moving out of the beta stage with Android following soon).
