### ISSUE TITLE
Access full-screen mode via URL

### ISSUE THREAD

**Issue by Isaac-the-Man** [wtg/Shuttle-Tracker-Web#123]
Automatically starts in full-screen mode if `https://web.shuttletracker.app/fullscreen` is the URL.

**Comment by qiud1** [comment]
This cannot be done as it goes against browser's security policy which requires fullscreen to be called by user action.

**Comment by Isaac-the-Man** [comment]
After careful consideration, we'll put this feature aside for now.

**Comment by Gerzer** [comment]
Sad 😢
