### ISSUE TITLE
Server status and full-screen buttons visible during full-screen animation on Firefox

### ISSUE THREAD

**Issue by michaelni678** [wtg/Shuttle-Tracker-Web#131]
https://user-images.githubusercontent.com/82001942/156452044-3d358dfd-1564-4bf2-8030-033f1eabda41.mp4

server status and fullscreen buttons are visible during firefox's fullscreen fadein/fadeout animation as seen in the video above. 
PS: The same buttons are used for when the map is fullscreened.

**Comment by michaelni678** [comment]
Which looks better?

https://user-images.githubusercontent.com/82001942/159628305-52e94733-e2ea-40bd-87e2-a7653e30a1cb.mp4

OR

https://user-images.githubusercontent.com/82001942/159628319-68cd5d92-8c1c-436b-8116-d5302bd3191d.mp4

(In the first one the status and enter fullscreen buttons stay when exiting fullscreen, in the second one they hide)


Also, I'm pretty sure there is no way to detect how long a user has their firefox fullscreen animation duration set to so I was planning on just setting it to the same time as the default settings.

Also I want to disable the buttons disappearing and stuff for non-firefox users since it only effects firefox but according to https://stackoverflow.com/questions/2324944/in-javascript-how-do-i-determine-if-my-current-browser-is-firefox-on-a-computer detecting browsers is a security risk or something. Is there a non-risky way to detect browser

**Comment by Gerzer** [comment]
I think that it’s fine to detect if the user agent indicates that the user is using Firefox. It’s not like we’re using it for anything that’s related to security, so if someone wants to spoof their user agent, then so be it.
