### ISSUE TITLE
Dynamic Schedule display issue

### ISSUE THREAD

**Issue by Gerzer** [wtg/Shuttle-Tracker-Web#136]
A recent update to the server API for our new Dynamic Schedule feature includes “AM” and “PM” labels in the JSON itself. The Web display of those data should be updated to omit its own duplicate labels.

![image](https://user-images.githubusercontent.com/5963974/158498726-de0af958-85d2-4ca4-9d43-4b23699e4603.jpeg)

**Comment by noahcussatti** [comment]
Should I implement make it so the AM and PM are converted to lowercase like it was before? Or should I keep them uppercase

**Comment by Gerzer** [comment]
> Should I implement it so the AM and PM are converted to lowercase like it was before? Or should I keep them uppercase?

It’s probably best just to display the string from the API as-is, which currently means leaving it with uppercase letters.
