### ISSUE TITLE
[New Feature] Add color blind mode

### ISSUE THREAD

**Issue by ACE3R2** [wtg/Shuttle-Tracker-Web#16]
Add option to change to colorblind mode; if in it, have different emojis for high quality/low quality buses.

**Comment by KPLJ** [comment]
Maybe consider using 🚌(bus) and 🚍(oncoming bus) to differentiate high/low quality buses

**Comment by KPLJ** [comment]
> Maybe consider using 🚌(bus) and 🚍(oncoming bus) to differentiate high/low quality buses

It's hard for users to know which emoji represents high/low-quality, even they are different bus emojis.
