### ISSUE TITLE
[New Feature] Add favicons

### ISSUE THREAD

**Issue by Isaac-the-Man** [wtg/Shuttle-Tracker-Web#6]
Add favicons to the shuttle tracker site. This includes:
- android icons of different sizes
- apple icons of different sizes
- regular favicons of different sizes

Also include a manifest file in the header to manage the icons. Checkout [this site](https://favicon.io/tutorials/what-is-a-favicon/) for more info. All of these files can be generated with an online tool.

**Comment by TheInspiredConjurer** [comment]
Hello. I'm new to Open Source. Can I work on this for Hacktoberfest?
