### ISSUE TITLE
[Bug Fix] Put Bus Icon above Stops Icon

### ISSUE THREAD

**Issue by FloofyPancakes** [wtg/Shuttle-Tracker-Web#7]
![IMG_3118](https://user-images.githubusercontent.com/80116509/135682669-1c535e47-f170-43e3-b8fc-dd9634e150c3.PNG)

bus stop markers covers the bus information. fix this by making bus stop transparent

**Comment by Gerzer** [comment]
@FloofyPancakes I do plan to fix this by making the bus information appear on top of the stop icons at all times. This isn't the right repository, though; this issue should've been posted in [the SwiftUI repository](https://github.com/wtg/Shuttle-Tracker-SwiftUI).

**Comment by KPLJ** [comment]
The issue with a screenshot of the web app is #17
