### ISSUE TITLE
Old web interface link should be darker/lighter

### ISSUE THREAD

**Issue by Zachary-Fernandes** [wtg/Shuttle-Tracker-Web#81]
**Is your feature request related to a problem? Please describe.**
I noticed the new Shuttle Tracker launched recently. At the bottom of the page, there is a link that says "Old Web Interface," and it lets you use Shuttle Tracker in its original appearance. The problem with this is the text color for this link does not contrast well enough with the background. On light mode, it is a light gray that almost blends in with the white background, and on dark mode, it is completely black and is hard to see on a near-black background.

**Describe the solution you'd like**
I think it would be best to make the text color on light mode darker and the text color on dark mode much brighter. With these changes, this text will contrast more with the background and be more visible to the user.

**Screenshots**
Light mode text color:

![lightmode](https://user-images.githubusercontent.com/32844805/142969774-3ce93dde-7097-4797-9590-f2819d93f2d3.PNG)

Dark mode text color:

![darkmode](https://user-images.githubusercontent.com/32844805/142969777-c18dac33-bc2c-4a0a-939f-7537ec6f4311.PNG)

**Comment by Gerzer** [comment]
@Zachary-Fernandes Thanks for the report! I completely agree. We’ll deploy a fix soon. I hope that you’re enjoying the *new* Shuttle Tracker!
