### ISSUE TITLE
Outdated link to TestFlight

### ISSUE THREAD

**Issue by Isaac-the-Man** [wtg/Shuttle-Tracker-Web#83]
This link redirects you to the testflight link, which is outdated since we have the app in appstore already. Link it to the official appstore link.
![image](https://user-images.githubusercontent.com/29915393/143060309-288e4b5c-70dc-4a48-91d2-51f88a1effbf.png)

**Comment by Gerzer** [comment]
The link should go to `https://shuttletracker.app/swiftui`, and the text should be changed to ”iOS/iPadOS/macOS App”.
