### ISSUE TITLE
Text wrapped on mobile device

### ISSUE THREAD

**Issue by Isaac-the-Man** [wtg/Shuttle-Tracker-Web#87]
![image](https://user-images.githubusercontent.com/29915393/143175170-69901d03-214a-4db1-aabc-483990b06331.png)

**Comment by Gerzer** [comment]
@Isaac-the-Man Are you referring to the "iOS/iPadOS/macOS App" link? If so, then is there a specific problem with the fact that it wraps? No matter what, it'll have to wrap to the next line once the width of the viewport is sufficiently small.

**Comment by Isaac-the-Man** [comment]
I was just thinking we could probably rephrase it in a much shorter manner so that it doesn't wrap.

**Comment by Gerzer** [comment]
> I was just thinking we could probably rephrase it in a much shorter manner so that it doesn't wrap.

That's a fair point. Now that the Android beta is out, how about we change the text to "Get the App" (or perhaps something even shorter) and have it link to the appropriate app for the user's current platform? I'll need to set up a new endpoint on the server that performs the redirection based on the user-agent string.

Another consideration: what about Windows and Linux users? Should we even show the link for people who are using platforms for which we have no native app? If so, then what should the link so? Let me know what you think.

**Comment by Isaac-the-Man** [comment]
@Gerzer I feel like not to over-complicate things. I suggest we get rid of the "This map refreshes every 5 seconds" line (everyone knew), and simiply put "Android App" on the left and "IOS App" on the right regardless of what platform they are on.

**Comment by Gerzer** [comment]
> @Gerzer I feel like not to over-complicate things. I suggest we get rid of the "This map refreshes every 5 seconds" line (everyone knew), and simiply put "Android App" on the left and "IOS App" on the right regardless of what platform they are on.
> 
> Something like this (inspector edit) ![image](https://user-images.githubusercontent.com/29915393/144075531-65f62909-6872-4476-a8d6-81104101cb7e.png)

I like that screenshot. I think that it's important to keep the "iOS/iPadOS/macOS App" label (instead of just "iOS App") because the same app is available on all three platforms. My only concern is that I don't really like the fact that there's a ton of blank space between the two links. What if we use half-width block buttons instead, at least when the viewport's width is sufficiently small? I don't think that the spacing is as much of an issue in larger viewports, and really long block buttons might look bad with the comparatively short label strings.

**Comment by Isaac-the-Man** [comment]
NO bro, think about the design.

**Comment by Gerzer** [comment]
> NO bro, think about the design.

Do you mean that block buttons might not look dissimilar enough from the schedule and settings containers? I think that you could make it clear that the buttons are tappable while the containers aren't by using outline buttons with transparent backgrounds, but perhaps you're right. Or am I misunderstanding you?

If you feel strongly that links are better than block buttons here, then that's perfectly fine.

**Comment by Isaac-the-Man** [comment]
Issue described [here](https://github.com/wtg/Shuttle-Tracker-Web/issues/94).
