### ISSUE TITLE
Full-screen mode is broken on iPhone

### ISSUE THREAD

**Issue by Isaac-the-Man** [wtg/Shuttle-Tracker-Web#91]
Doesn't work on iphone
![image](https://user-images.githubusercontent.com/29915393/145033413-e966b324-7cb6-4740-9183-28a39e23db45.png)

**Comment by Gerzer** [comment]
@Isaac-the-Man That’s not good! I’ll revert the production deployment for now, at least until this bug is fixed.

**Comment by Isaac-the-Man** [comment]
It's an iPhone problem only. I'll probably remove this feature for all mobile device.

**Comment by Gerzer** [comment]
> It's an iPhone problem only. I'll probably remove this feature for all mobile device.

Yeah, that seems like a reasonable solution. There’s not much of a need for a full-screen mode on mobile devices, especially since we want that users use the native apps instead.
