### ISSUE TITLE
Move iOS/iPadOS/macOS download link to Settings block to fix mobile view

### ISSUE THREAD

**Issue by huynchu** [wtg/Shuttle-Tracker-Web#94]
![image](https://user-images.githubusercontent.com/90888002/145647395-070e95eb-4d27-4dde-8c03-f292497ceff3.png)

**Comment by Gerzer** [comment]
Is Settings the best place for it? What about putting it directly under the Settings block?

**Comment by Isaac-the-Man** [comment]
I suggest we just move it to the footer, on the same level as the link "old web interface".

**Comment by Gerzer** [comment]
> I suggest we just move it to the footer, on the same level as the link "old web interface".

That works. While we're at it, we should also add a link to the Android app.

**Comment by Isaac-the-Man** [comment]
Move the links (link to IOS and Android) down to the copyright section, where the "Old Web Interface" link is. Ignore the "This map refreshes every 5 seconds" message for now. Remove the component (Footer) that holds the original links in `Home.vue`, but do not remove the original file `Footer.vue`. The result look something like below:
![image](https://user-images.githubusercontent.com/29915393/152715965-ce49b659-dc61-4b8e-abdf-89edc61bdf8a.png)
