### ISSUE TITLE
Annoucements animation is way too fast

### ISSUE THREAD

**Issue by huynchu** [wtg/Shuttle-Tracker-Web#98]
Scrolling animation of the announcement banner is too fast on large screens (non-mobile widths).

**Comment by Gerzer** [comment]
Yeah, I noticed this when I posted our longest announcement yet. Is the issue that the total animation time is fixed, regardless of how long the message is?

**Comment by huynchu** [comment]
Yup, that is the issue

**Comment by huynchu** [comment]
Also, I feel like we should change the announcements UI altogether on web. I've tested slower animation times but this style of announcement is very hard to read regardless of the animation speed (other than making it super slow).

**Comment by michaelni678** [comment]
How about we make it so that there is no animation if the announcement is short enough to fit on the screen? And if the announcement is too long the animation will play slowly but if you hold your mouse/finger on it it will stop and be draggable (as in you can drag it left/right to reverse/fast-forward the animation a bit to scroll)

**Comment by Gerzer** [comment]
> How about we make it so that there is no animation if the announcement is short enough to fit on the screen? And if the announcement is too long the animation will play slowly but if you hold your mouse/finger on it it will stop and be draggable (as in you can drag it left/right to reverse/fast-forward the animation as if you're scrolling)

I like this idea, though I suggest that let the user scroll the announcement banner instead of dragging it.

**Comment by michaelni678** [comment]
> > How about we make it so that there is no animation if the announcement is short enough to fit on the screen? And if the announcement is too long the animation will play slowly but if you hold your mouse/finger on it it will stop and be draggable (as in you can drag it left/right to reverse/fast-forward the animation as if you're scrolling)
> 
> I like this idea, though I suggest that we let the user scroll the announcement banner instead of dragging it.

alright, ill start working on it
